### ISSUE TITLE
Make `ProgramJson` serializable

### ISSUE THREAD

**Issue by haroune-mohammedi** [lambdaclass/cairo-rs#856] opened 2023-02-22 12:08 UTC
**Is your feature request related to a problem? Please describe.**
`ProgramJson` doesn't implement `Serialize` which makes it impossible to use it if we need to save compiled cairo programs represented as `ProgramJson` to disk which is the case for `cairo-foundry`'s [caching machanisme](https://github.com/open-dust/cairo-foundry/blob/cf91f94d468314033d90d72948b041b272b83720/src/compile/cache/mod.rs#L76).

Also, serializing the `ProgramJson` is mandatory if we want to compile cairo programs in Rust instead of using Python's `cairo-compile` implementation

**Describe the solution you'd like**
Implement `Serialize` for `ProgramJson` and all other dependent strcutres:
- `Felt`
- `ValueAddress`
- `Vec<MaybeRelocatable>`
- `HashMap<String, usize>`

**Describe alternatives you've considered**
In `cairo-foundry` we're using `serde_json::Value` to represent compiled cairo programs, then we use `serde_json:from_value` whenever we need a `ProgramJson` instance

```rust
#[derive(Serialize, Deserialize, Debug)]
pub struct CompileCacheItem {
	pub hash: u64,
	// TODO: make program_json: ProgramJson, we're not using it right now because
	// it doesn't implement Serialize
	pub program_json: Value,
}
```
https://github.com/open-dust/cairo-foundry/blob/cf91f94d468314033d90d72948b041b272b83720/src/compile/cache/mod.rs#L76

```rust
pub fn compile(path_to_cairo_file: &PathBuf) -> Result<ProgramJson, Error> {
        ...

	let compile_output = compile_cairo_file(path_to_cairo_file)?;

	let program_json: Value = serde_json::from_slice(&compile_output)?;

	let cache = CompileCacheItem {
		program_json: program_json.clone(),
		hash,
	};

	let program_json: ProgramJson = serde_json::from_value(program_json)?;

	cache.write(&cache_path)?;

	Ok(program_json)
...
```
https://github.com/open-dust/cairo-foundry/blob/main/src/compile/mod.rs#L87

**Additional context**

**Comment by haroune-mohammedi** [comment] 2023-02-23 10:27
Can someone assign it to me please ? Or should I open a PR and start working directly ?

**Comment by Jrigada** [comment] 2023-02-23 16:05
Hi Haroune, can you explain us a little bit more the use case of this feature? Because before creating the programsJson struct you should have the json file.

**Comment by haroune-mohammedi** [comment] 2023-02-24 10:18
@Jrigada We are caching compiled cairo programs to disk, that's why we need to be able to serialize the `ProgramJson` struct instead of going back and forth to `serde::Value` to be able to serialize them

Also, serializing the `ProgramJson` would be useful when we want to write a cairo compiler using Rust.

**Comment by Jrigada** [comment] 2023-02-24 14:52
Sorry I am probably being dumb here, but when you say that you want to cache the compiled cairo program you mean saving the json in disk? If you have the json you wouldn't need to recompile it again.

**Comment by haroune-mohammedi** [comment] 2023-02-24 16:11
> Sorry I am probably being dumb here, but when you say that you want to cache the compiled cairo program you mean saving the json in disk? If you have the json you wouldn't need to recompile it again.

Exactly, caching means saving to disk.

**Comment by fmoletta** [comment] 2023-03-01 19:12
Hello! I saw that you are currently capturing the compiled program outputted by `cairo-compile` from stdout, deserializing it into a `ProgramJson` and then serializing it again to save it as a file in the cache system. Is is possible to simplify this process by compiling the cairo program to a json file and using that file in the cache system?

**Comment by haroune-mohammedi** [comment] 2023-03-02 10:00
@fmoletta but that'd cause a little more mess, `cairo-compile` will write the file to disk, we'll read it back and delete it right away, after that we construct a `CompileCacheItem{program_json: Value, hash: u64}` and save it to disk, the issue is that  we have to use `Value` because `ProgramJson` doesn't implement `Serialize`

We'll do something like this:

```mermaid
  flowchart LR;
      main.cairo --> cairo-compile
      cairo-compile-->File;
      File<--read and delete-->ProgramJson;
      ProgramJson-->Value;
      Value-->CompileCacheItem;
      main.cairo-->hash;
      hash-->CompileCacheItem;
      CompileCacheItem-->CacheFile;
```

Instead of what we are currently doing:

```mermaid
  flowchart LR;
      main.cairo --> cairo-compile
      cairo-compile-->ProgramJson;
      ProgramJson-->Value;
      Value-->CompileCacheItem;
      main.cairo-->hash;
      hash-->CompileCacheItem;
      CompileCacheItem-->CacheFile;
```

What we want is to not convert to `Value` at all and define our `CompileCacheItem` using `ProgramJson`:

```mermaid
  flowchart LR;
      main.cairo --> cairo-compile
      cairo-compile-->ProgramJson;
      ProgramJson-->CompileCacheItem;
      main.cairo-->hash;
      hash-->CompileCacheItem;
      CompileCacheItem-->CacheFile;
```

**Comment by Oppen** [comment] 2023-03-02 15:03
Hello @haroune-mohammedi. I'm trying to understand the issue as well, so I have a few questions.

I see in the diagrams the VM doesn't seem to be involved. This project, at least currently, is only about execution of compiled Cairo programs. It doesn't concern itself with compilation, and there are no current plans for it to do so. In any case, a potential compiler should be able to dump the built artifacts itself, even if only for better validation.

Regarding the caching model, I don't see a reason to either delete the file created in diagram one instead of using it as the cached value itself. I'm also unsure going through `serde_json::Value` comes with any relevant performance hit. Is there a PoC where we see actual gains from this added complexity in the VM?
Even if there were, I see the case for the already populated cache doesn't involve `Value` anyway, so unless the gains are really big it doesn't make a ton of sense to optimize the unpopulated cache case that much if it won't affect the (expected) more common case of a cache hit.

Wouldn't serializing the parsed program just produce the same kind of bytecode the machine consumes? This means we need to produce that file somewhere else anyway. That sounds like something `tee(1)` could solve in a simpler way.

In terms of implementation, how involved the code would be? Is it just adding a derive macro or writing a full fledged serializing routine that we would have to maintain? What would happen when we need to support different serialization layouts, such as starknet compiled programs?

I think maybe including in the conversation @tdelabro and the cairo-foundry maintainers could be a good idea, it would help us see if we're missing something in the picture.
@juanbono also told me he wanted to take a look at this, he said he might have some idea to meet in the middle.

**Comment by Oppen** [comment] 2023-04-20 02:03
There's another question that tickles me re-reading the issue. Why is `ProgramJson` cached rather than `Program`? Wouldn't it make more sense to save as much processing as possible? I'm thinking it may even be a better idea to write some basic `bincode` (tentatively) methods for serialization and deserialization of that structure instead.

**Comment by Oppen** [comment] 2023-04-20 02:17
Ahhh, I see, the issue is that you need to serialize that cache from the item itself. That's what I was missing.
I still think the task requires a bit more thought than just deriving `Serialize`, tho. We need to define a format we can commit to and to specify how that serializes and deserializes to `ProgramJson`. Otherwise, we marry to one in-memory representation that may not be best in the future. The same applies to `Program` (but in the case of `Program`, I think we save much more post-processing if that's what we pick).

**Comment by tdelabro** [comment] 2023-04-20 15:29
The project has been halted(killed) by starknet. So we actually don't need this feature anymore.
You can close it. But it's great if it gave you some ideas ;)

**Comment by Oppen** [comment] 2023-04-20 16:34
Oh, that's sad. It looked interesting :(
Is there anything around/planned to fill the niche?

**Comment by tdelabro** [comment] 2023-04-20 16:55
There may be something, coming soon 🤫

**Closed** 2023-04-20 17:32 UTC
Labels: enhancement
